### ISSUE TITLE
Check user owned repos and repos user is a collaborator with self enum.

### ISSUE THREAD

**Issue by ankushgoel27** [AdnaneKhan/Gato-X#20]
**Describe the bug**
It seems like this tool doesn't enum internal repos and only scans public and private repos. Correct me if I am wrong. It would be great if it can also scan for internal  repos.

**To Reproduce**

**Expected behavior**

**Screenshots**

** Environment (please complete the following information):**
- Python Version: [e.g. 3.11]

**Additional context**

**Comment by AdnaneKhan** [comment]
Gato-X should support internal repositories, if not then that is a bug.

Internal repositories are only supported for GitHub Enterprise organizations - can you verify that:

- The organization you are trying to enumerate actually has internal repositories.
- You are seeing an internal repository using a PAT that Gato-X is not picking up using that same PAT.

In the JSON response Gato-X only sets repos as public or private (includes private and internal) because it populates the repo object from the GraphQL result for a repo.

**Comment by ankushgoel27** [comment]
my apologies, it does pick up internal repos. but when doing `enum -s`, it doesn't pick up repos from its own account that comes under the `user/reops` endpoint but only target the org repos

**Comment by AdnaneKhan** [comment]
Ah, ok thanks for the clarification. That’s a good callout - you can now get the user’s own repos by running `gato-x e -t theUser` (previously it only worked with orgs), but it won’t enumerate repos that the user is a collaborator on.

I’m going to convert this into an issue that I’ll aim to add with the next minor release along with multithreaded querying. Self enum will continue to check each org, but then it will check repos that the user owns and repos that the user is a collaborator on.

Thanks for bringing this up - it’ll be easy to add now that the user repo enum code is in.

**Comment by AdnaneKhan** [comment]
@ankushgoel27 I've added an initial version of this functionality in the `enumerate_user_owned_repos` branch. Feel free to check out the changes and give feedback in #22.

**Comment by ankushgoel27** [comment]
Thank, I will check it out and let you know.

**Comment by ankushgoel27** [comment]
have u looked into the github token scope - `manage_runners:enterprise` ?

**Comment by ankushgoel27** [comment]
Hi Adnan,

I tested the branch. I does enumerate the self reops first from the user/repos endpoint and then targets the org repos. However, the user/repos and orgs/$org/repos could contain the same repositories so it will be scanning the same repos again while doing the org scan which will be redundant/duplicate and also waste time and API calls. is there a way to make it not do that?

also, mention that the target `-t` could be an org or a repo in the help `-h`.

**Comment by ankushgoel27** [comment]
Hello,

I have a question. how did you manage to execute code on the runner. Isnt the workflow executed is based on the workflow file in the base repository, and not on the fork. so how does a PR from fork executes code on the self hosted runner?

**Comment by AdnaneKhan** [comment]
> Hi Adnan,
> 
> I tested the branch. It does enumerate the self repos first from the `user/repos` endpoint and then targets the org repos. However, the `user/repos` and `orgs/$org/repos` could contain the same repositories so it will be scanning the same repos again while doing the org scan which will be redundant/duplicate and also waste time and API calls. Is there a way to make it so that it does not do that?
> 
> also, mention that the target `-t` could be an org or a repo in the help `-h`.

So it should pass a parameter that will exclude repos through org membership in the first call (take a look at the API docs for that call). Regarding the second point I’ll update the help text that you can target an organization or a user with `-t`.

**Comment by AdnaneKhan** [comment]
> Hello,
> 
> I have a question. how did you manage to execute code on the runner. Isnt the workflow executed is based on the workflow file in the base repository, and not on the fork. so how does a PR from fork executes code on the self hosted runner?

Well this is more of a general Gato-X question but the way it works is that workflows on `pull_request` use the workflow file and code defined in the merge commit, NOT the code from the base.

**Comment by ankushgoel27** [comment]
when doing -t $username, it targets only the user repos. 

But when doing gato-x ennum -s, it targets both user(both personal and collab repos) and org repos which is expected however the endpoints could return redundant repos which I think is unnecessary to maintain speed and efficiency
