### ISSUE TITLE
Use of GitHub App installation access token not allowed

### ISSUE THREAD

**Issue by varunsh-coder** [AdnaneKhan/Gato-X#23]
**Describe the bug**
There is code that validates token format, and app installation access tokens are not allowed
https://github.com/AdnaneKhan/Gato-X/blob/e0ca92d4d3b62fd690d35ee2591584308a21138c/gatox/cli/cli.py#L91

Such tokens start with `ghs_`
https://github.blog/engineering/platform-security/behind-githubs-new-authentication-token-formats/#identifiable-prefixes

**To Reproduce**
Use an App installation access token
You will see this error
```
Provided GitHub PAT is malformed!
```

**Expected behavior**
App installation access tokens should also work

**Comment by AdnaneKhan** [comment]
There is a bit to unpack with this behavior - Gato-X is primarily designed around the GitHub tokens that have the legacy scopes - that is OAuth scopes associated with Classic PATs, OAuth tokens (such as those for the GitHub CLI). Gato-X's enumeration flow is designed with at least a `repo` scoped token in mind. This all goes back to the original design of Gato being a tool written by Red Team operators for Red Teamers.

A GitHub App U2S or S2S token on the other hand has fine grained scopes selected at installation time, so Gato-X currently does not have a way to determine if the permissions of the token will work with the various enumeration calls Gato-X performs (IIRC there is no way to check what permissions a fine grained or app U2S or S2S token has).

To work towards a way Gato-X can function with app tokens, what use case do you envision? Is it running at the organization level or running on a single repository? Do you want visibility into self-hosted runners via run-log analysis or just the SAST features against workflows.

I think the solve would be to add an app operation mode that takes the app token and a list of repositories that token is authorized to access. For the enumeration flow, Gato-X will need `actions: read` (for run logs) and `contents: read` (to retrieve workflow YAML files).

**Comment by varunsh-coder** [comment]
Hi @AdnaneKhan thanks for the quick response!

The use case is to run at a repo level for the enumeration flow for public repos. The token has `actions: read` but given that it will run on a public repo, I believe explicit `contents: read` should not be required.

**Comment by AdnaneKhan** [comment]
> Hi @AdnaneKhan thanks for the quick response!
> 
> The use case is to run at a repo level for the enumeration flow for public repos. The token has `actions: read` but given that it will run on a public repo, I believe explicit `contents: read` should not be required.

I will investigate adding an app auth flag for the single repository enumeration that works with a fine grained token. It should be a simple check to the param validation and the pre-API call scope check (as there is no scope introspection for app tokens).

Longer term I want to add support for fine grained and app tokens to essentially brute force permissions/repo access of a token. That will be a useful feature for the red team side of the tool. Going to wait until I finish the multiprocessing overhaul, though.

**Comment by AdnaneKhan** [comment]
I've improved the validation to be clear that the token is not malformed, just currently not supported. I also added a feature request in #25 to support your automation use case.

I'm going to follow up with another update that allows fine grained and app tokens with a message that says they are only supported for public repo enumeration.

**Comment by AdnaneKhan** [comment]
Moved to #25 for the new feature and tracking changes in #37.
